main/urls.py
from django.contrib import admin
from django.urls import path

from blogs.api import BlogsAPI, BlogDetailAPI
from blogs.views import LatestBlogsView, BlogDetailView, NewBlogView, BlogListView, UserBlogView
from users.api import UsersAPI, UserDetailAPI
from users.views import LoginView, LogoutView, SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    # Users
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path("signup/", SignUpView.as_view(), name="signup"),

    # Blogs
    path('new-post', NewBlogView.as_view(), name='new_blog'),
    path('blogs/<str:owner>/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('', LatestBlogsView.as_view(), name='home'),
    path('blogs/', BlogListView.as_view(), name='blog_all'),
    path('blogs/<str:owner>/', UserBlogView.as_view(), name='userblog'),

    # API
    path('api/users/<int:pk>', UserDetailAPI.as_view(), name='user_detail_api'),
    path('api/users/', UsersAPI.as_view(), name='user_api'),
    path('api/blogs/<int:pk>', BlogDetailAPI.as_view(), name='blog_detail_api'),
    path('api/blogs/', BlogsAPI.as_view(), name='blog_api')
]

blogs/models.py
from django.contrib.auth.models import User
from django.db import models


class Blog(models.Model):

    IMPORTANT = 'IMP'
    INFORMATION = 'INF'
    NOTE = 'NOT'

    LICENSES = [
        [IMPORTANT, 'Important'],
        [INFORMATION, 'Information'],
        [NOTE, 'Note']
    ]

    PUBLIC = 'PUB'
    PRIVATE = 'PRI'

    VISIBILITY = [
        [PUBLIC, 'Public'],
        [PRIVATE, 'Private']
    ]

    title = models.CharField(max_length=150)
    text = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    url = models.URLField()
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=3, choices=LICENSES, default=INFORMATION)
    owner = models.ForeignKey(User, related_name='blogs', on_delete=models.CASCADE)
    visibility = models.CharField(max_length=3, choices=VISIBILITY, default=PUBLIC)

    def __str__(self):
        return self.title

blogs/forms.py
from django.forms import ModelForm

from blogs.models import Blog


class BlogForm(ModelForm):

    class Meta:
        model = Blog
        fields = ['title', 'text', 'description', 'url', 'category']

blogs/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView

from blogs.forms import BlogForm
from blogs.models import Blog


class LatestBlogsView(View):
    def get(self, request):
        # Recuperamos los últimos posts de la base de datos
        blogs = Blog.objects.filter(visibility=Blog.PUBLIC).order_by('-creation_date').select_related('owner')

        # Creamos el contexto para pasarle los post a la plantilla
        context = {'latest_blog': blogs[:5]}

        # Crear respuesta HTML con las posts
        html = render(request, 'latest.html', context)

        # Devolver la respuesta HTTP
        return HttpResponse(html)


class BlogDetailView(View):
    def get(self, request, pk, owner):
        # Recuperar el blog seleccionado de la base de datos
        blogs = get_object_or_404(Blog.objects.select_related('owner'), pk=pk, visibility=Blog.PUBLIC)
        owner = owner

        # Crear un contexto para pasar la información a la plantilla
        context = dict(owner=owner, blog=blogs)

        # Renderizar plantilla
        html = render(request, 'detail.html', context)

        # Devolver respuesta HTTP
        return HttpResponse(html)


class NewBlogView(LoginRequiredMixin, View):
    def get(self, request):
        form = BlogForm()
        context = {'form': form}
        return render(request, 'new-post.html', context)

    def post(self, request):
        blog = Blog()
        blog.owner = request.user
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            new_blog = form.save()
            messages.success(request, 'Post creado correctamente con ID {0}'.format(new_blog.pk))
            form = BlogForm()
        context = {'form': form}
        return render(request, 'new-post.html', context)


class BlogListView(View):
    def get(self, request):
        # Recuperamos los últimos posts de la base de datos
        blogs = Blog.objects.all().order_by('-creation_date')

        # Creamos el contexto para pasarle los post a la plantilla
        context = {'latest_blog': blogs}

        # Crear respuesta HTML con las posts
        html = render(request, 'list.html', context)

        # Devolver la respuesta HTTP
        return HttpResponse(html)


class BlogList(object):

    def get_queryset(self):
        queryset = Blog.objects.select_related('owner').order_by('-creation_date')
        if self.request.user.is_authenticated:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class UserBlogView(BlogList, ListView):

    template_name = 'blogusuario.html'

blogs/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>Wordplease Blog</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
                font-family: "Open Sans", sans-serif;
                font-size: 15px;
                background-color: #fdfdfd;
            }
            .masthead {
                background: #3398E1;
                height: auto;
                padding-bottom: 15px;
                box-shadow: 0 16px 48px #E3E7EB;
                padding-top: 10px;
            }
            .footer_text {
                color: gray;
            }
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
            }
            li {
                float: left;
            }
            li a {
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }
            .login-card {
                margin: 10px 10px;
            }
    </style>
<header class="masthead">
    <div class="overlay">
        <div class="container">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <a href="{% url 'home' %}" style="text-decoration: none">
                        <h3 class="site-heading my-4 mt-3 text-white"> Welcome to WORDPLEASE Blog </h3></a>
                        <ul>
                            <li><a style="text-decoration: none" href="{% url 'home' %}">Home</p></a>
                            <li><a style="text-decoration: none" href="{% url 'blog_all' %}">Blogs</p></a>
                            <li><a style="text-decoration: none" href="{% url 'new_blog' %}">New Post</p></a>
                            <li><a style="text-decoration: none" href="{% url 'home' %}">Signup</p></a>
                            {% if user.is_authenticated %} <li><a style="text-decoration: none" href="{% url 'logout' %}">Logout</a></li>
                            {% else %} <li><a style="text-decoration: none" href="{% url 'login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                </div>
            </div>
        </div>
    </div>
</header>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="footer_text m-0 text-center">Copyright &copy; Wordplease Blog</p>
        </footer>
    </body>
</html>

blogs/templates/blogusuario.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Open Sans", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
       .right {
  float: right;
}
    .center {
  text-align: center;
}
</style>

<div class="container">
    <h1 class="center">Users Posts</h1>
        <!-- Blog Entries Column -->
    {% for blog in object_list %}
        <div>
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ blog.title }}</h2>
                    <h4 class="card-title"> {{ blog.text }}</h4>
                    <p class="card-text text-muted h6">{{ blog.owner }} | Published on {{ blog.creation_date|date:'d/m/Y' }}</p>
                    <p class="card-text">{{blog.description|slice:":200" }}</p>
                    <a href="{% url 'blog_detail' blog.owner blog.pk %}">
                    <img src="{{ blog.url }}" alt="{{ blog.description }}" title="{{ blog.title }}" by {{ blog.owner.first_name }} {{ blog.owner.last_name }} height="200"></a>
                    <a href="{% url 'blog_detail' blog.owner blog.pk %}" class="right"> Read More &rarr;</a>
                </div>
            </div>
    {% endfor %}
        </div>
</div>
{%endblock%}

blogs/templates/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div>
      <div class="card-body">
          <h1>{% block title %} {{ blog.title }} {% endblock title %}</h1>
          <img src="{{ blog.url }}" alt="{{ blog.description }}" title="{{ blog.title }}" width="400">
          <p class=" text-muted"> </p>
          <h4 class="card-title"> {{ blog.text }}</h4>
          <p class="card-text ">{{ blog.description | safe }} </p>
          <p class=" text-muted">{{ blog.owner }} | Published on {{ blog.creation_date|date:'d/m/Y'}} by {{ blog.owner.first_name }} {{ blog.owner.last_name }}</p>
          <a href="{% url 'home' %}" class="btn btn-primary"> Return</a>
      </div>
    </div>
</div>

{% endblock content %}

blogs/templates/index.html
<style>
    body {
        font-family: "Open Sans", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay">
    <div class="container">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Wordplease Blog </h3>
                    <p class="text-light">We Love Django!</p>
                </div>
            </div>
    </div>
</header>
<div class="container">
        <!-- Blog Entries Column -->
        <div>
            {% for blog in blog_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ blog.title }}</h2>
                    <p class="card-text text-muted h6">{{ blog.creation_date }} | {{ blog.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>

                </div>
            </div>
            {% endfor %}
        </div>
</div>

blogs/templates/latest.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Open Sans", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .right {
  float: right;
}
</style>

<div class="container">

        <!-- Blog Entries Column -->
        <div>
            {% for blog in latest_blog %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ blog.title }}</h2>
                    <h4 class="card-title"> {{ blog.text }}</h4>
                    <p class="card-text text-muted h6">{{ blog.owner }} | Published on {{ blog.creation_date|date:'d/m/Y' }}</p>
                    <p class="card-text">{{blog.description|slice:":200" }}</p>
                    <a href="{% url 'blog_detail' blog.owner blog.pk %}">
                    <img src="{{ blog.url }}" alt="{{ blog.description }}" title="{{ blog.title }}" by {{ blog.owner.first_name }} {{ blog.owner.last_name }} height="200"></a>
                    <a href="{% url 'blog_detail' blog.owner blog.pk %}" class="right"> Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
</div>
{%endblock%}

blogs/templates/list.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Open Sans", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .right {
  float: right;
}
</style>

<div class="container">
        <!-- Blog Entries Column -->
    <h1 style="text-align: center">All Posts</h1>
        <div>
            {% for blog in latest_blog %}
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="card-title">{{ blog.title }} </h4>
                    <h5 class="card-title"> {{ blog.text }}</h5>
                    <p class="card-text text-muted h6">{{ blog.owner }} | Published on {{ blog.creation_date|date:'d/m/Y' }}</p>
                    <p class="card-text">{{blog.description|slice:":25" }}
                    <a href="{% url 'blog_detail' blog.owner blog.pk %}" class="right"> Read More &rarr;</a></p>
                </div>
            </div>
            {% endfor %}
        </div>
</div>
{%endblock%}

blogs/templates/new-post.html
{% extends 'base.html' %}
{% block head_title %} New blog {% endblock %}
{% block main_title %} New blog {% endblock %}

{% block content %}

    <div class="container">
        <div>
            <div class="card-body">
                {% for message in messages %}
                    <p style="color:green">{{ message }}</p>
                {% endfor %}
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Save Post</button>
                    </form>
            </div>
        </div>
    </div>
{% endblock %} 